//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionIncidenciasInformaticas.Backend.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class incidencia
    {
        public int num_incidencia { get; set; }
        public string tipo_incidencia { get; set; }
        public System.DateTime fecha_incidencia { get; set; }
        public System.DateTime fecha_introduccion { get; set; }
        public string aula_ubicacion { get; set; }
        public string descripcion_incidencia { get; set; }
        public string observaciones { get; set; }
        public Nullable<System.DateTime> fecha_resolución { get; set; }
        public int estados_codigo_estado { get; set; }
        public int departamento_codigo_dep { get; set; }
        public string profesor_dni { get; set; }
        public Nullable<double> tiempo_invertido { get; set; }
        public byte[] info_acompanyada { get; set; }
        public Nullable<int> hardware_id_incidencia_hw { get; set; }
        public string dni_responsable { get; set; }
    
        public virtual departamento departamento { get; set; }
        public virtual estados estados { get; set; }
        public virtual hardware hardware { get; set; }
        public virtual profesor profesor { get; set; }
        public virtual profesor profesor1 { get; set; }
    }
}
